services:
  postgres:
    image: postgres:15
    container_name: olist_postgres
    environment:
      POSTGRES_DB: olist_dw
      POSTGRES_USER: olist_user
      POSTGRES_PASSWORD: olist_pass
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
